DEFINE 

---- MODEL MEASURES BEGIN ----
MEASURE 'Internet Sales'[Internet Total Units Year To Date PY] = CALCULATE(
[Internet Total Units],DATESYTD(SAMEPERIODLASTYEAR('Date'[Date])))

MEASURE 'Internet Sales'[Internet Total Units YTD PY% (Ineficiente)] = 
IF(ISBLANK([Internet Total Units Year To Date PY]),0, [Internet Total Units Year To Date]/[Internet Total Units Year To Date PY])
---- MODEL MEASURES END ----

MEASURE 'Internet Sales'[Internet Total Units Year To Date] = CALCULATE(
[Internet Total Units],DATESYTD('Date'[Date]))

MEASURE 'Internet Sales'[Internet Total Units YTD PY% (fixed)] = 
VAR denom = [Internet Total Units Year To Date PY]
VAR num = [Internet Total Units Year To Date]

RETURN
--IF(ISBLANK(denom),0, num/denom)
DIVIDE(num,denom,0)


EVALUATE
SUMMARIZECOLUMNS(
'Date'[Date],
"Total Units",[Internet Total Units],
"Total Units YTD",[Internet Total Units Year To Date],
"Total Units YTD PY", [Internet Total Units Year To Date PY],
"Total Units YTD PY%", [Internet Total Units YTD PY% (Ineficiente)],
"Total Units YTD PY% fixed", [Internet Total Units YTD PY% (fixed)]
)